"""Parse Paket manifest + lockfile for .NET dependencies.

Paket is an alternative .NET package manager popular in F# and some
enterprise .NET shops. It coexists with the standard NuGet client and
fetches from the same ``api.nuget.org`` registry for its NUGET group.

The two relevant files are:

* **``paket.dependencies``** — top-level workspace manifest. Text format
  with optional ``group`` sections. Example:

  .. code-block:: text

      source https://api.nuget.org/v3/index.json

      nuget Newtonsoft.Json ~> 13.0
      nuget Serilog >= 3.1

      group Test
          source https://api.nuget.org/v3/index.json
          nuget xunit
          nuget FsCheck

      group Build
          source https://api.nuget.org/v3/index.json
          nuget Fake.Core.Target

* **``paket.lock``** — resolved lockfile, generated by ``paket install``.
  Carries the full transitive graph with versions pinned. Example:

  .. code-block:: text

      NUGET
        remote: https://api.nuget.org/v3/index.json
          Newtonsoft.Json (13.0.1)
          Serilog (3.1.1)
            FSharp.Core (>= 5.0)
          xunit (2.6.1)
      GROUP Test
      NUGET
        remote: https://api.nuget.org/v3/index.json
          FsCheck (2.16.5)
            FSharp.Core (>= 5.0)

Group → dev/prod mapping:

* The default group (no ``group`` directive) and explicit ``group Main``
  → PROD.
* ``group Test`` → DEV.
* ``group Build`` / ``group Tools`` / any other custom group → DEV
  (conservative — Maven's scope mapping uses the same posture, classifying
  unknown scopes as DEV to avoid runtime exposure).

Source kinds:

* ``source https://api.nuget.org/...`` → fetched via the standard NuGet
  resolver path.
* ``git https://...``, ``github user/repo``, ``http URL`` → **not honored**.
  Per the manifest+registry-only paradigm, only the NUGET source is
  resolved. Packages declared via non-NUGET sources emit ``Dependency``
  entries with empty ``version_constraint`` (so the license resolver
  surfaces them as UNKNOWN rather than silently dropping them).

This parser does NOT cross-validate ``paket.dependencies`` against
``paket.lock``. When the lockfile is present, the transitive walker
treats it as source-of-truth (lockfile-first); the manifest contributes
direct-dep roots that the walker uses for reachability attribution.
"""

from __future__ import annotations

import re
from pathlib import Path

from licenseal.discovery._read import decode_text
from licenseal.discovery._walk import walk_project_files
from licenseal.models import Dependency, DependencyGroup, Ecosystem

_DEPENDENCIES_FILENAME = "paket.dependencies"
_LOCK_FILENAME = "paket.lock"

# Matches ``nuget <PackageName> [<VersionConstraint>]`` lines. Version
# constraint is optional — Paket allows ``nuget X`` to mean "any version"
# (Paket's resolver picks the latest, but for license-discovery the
# missing-version handling is the same as elsewhere: emit empty, let the
# resolver UNKNOWN).
_NUGET_LINE_RE = re.compile(r"^\s*nuget\s+(\S+)(?:\s+(.+))?$", re.IGNORECASE)

# Matches a Paket lockfile entry: ``    Package.Name (version)`` or
# ``      Sub.Dep (>= 1.0)``. Leading whitespace controls depth:
# 4 spaces = direct, more = transitive. The version is captured WITHIN
# the parentheses. Empty-parens cases (rare) yield empty version.
_LOCK_ENTRY_RE = re.compile(r"^(\s+)(\S+)\s*\(([^)]*)\)\s*$")

# Group-line shapes:
# In paket.dependencies: ``group <name>`` (lowercase ``group`` keyword).
# In paket.lock: ``GROUP <name>`` (uppercase).
_GROUP_DEPS_RE = re.compile(r"^\s*group\s+(\S+)\s*$", re.IGNORECASE)
_GROUP_LOCK_RE = re.compile(r"^GROUP\s+(\S+)\s*$")

# Source-line markers in the lockfile. Each source-section header
# changes how we treat following entries. Only NUGET sections are
# resolvable against ``api.nuget.org``.
_NUGET_SOURCE_LINE = "NUGET"
_NON_NUGET_SOURCE_LINES = frozenset({"GIT", "GITHUB", "HTTP"})

_DEV_GROUP_NAMES = frozenset({"test", "build", "tools"})


def _group_to_dependency_group(group_name: str) -> DependencyGroup:
    """Map a Paket group name to ``DependencyGroup``.

    ``Main`` (the default group) and unknown-but-not-obviously-dev names
    stay PROD; ``Test``, ``Build``, ``Tools``, and any other recognized
    dev-class group go DEV. Case-insensitive match.
    """
    normalized = group_name.strip().lower()
    if normalized in _DEV_GROUP_NAMES or normalized.endswith("test"):
        return DependencyGroup.DEV
    return DependencyGroup.PROD


def _parse_paket_dependencies_text(text: str) -> list[tuple[str, str, DependencyGroup]]:
    """Parse ``paket.dependencies`` text into ``(name, version_constraint, group)`` tuples.

    Only ``nuget`` source lines are emitted; ``git``, ``github``, ``http``
    sources are silently skipped (out of registry-only scope). Group
    membership is tracked via the running-group state; the implicit
    pre-group section is PROD.

    Version constraints (``~> 13.0``, ``>= 3.1``, etc.) are kept as-is —
    the resolver's version-extraction logic in :mod:`.resolvers.nuget`
    handles range constraints by picking a conservative pinned version.
    """
    out: list[tuple[str, str, DependencyGroup]] = []
    current_group = DependencyGroup.PROD
    for raw_line in text.splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("//") or stripped.startswith("#"):
            continue
        group_match = _GROUP_DEPS_RE.match(raw_line)
        if group_match:
            current_group = _group_to_dependency_group(group_match.group(1))
            continue
        nuget_match = _NUGET_LINE_RE.match(raw_line)
        if not nuget_match:
            continue
        name = nuget_match.group(1).strip()
        constraint_raw = (nuget_match.group(2) or "").strip()
        # Strip trailing inline ``// comment`` if present.
        if "//" in constraint_raw:
            constraint_raw = constraint_raw.split("//", 1)[0].strip()
        out.append((name, constraint_raw, current_group))
    return out


def _parse_paket_lock_text(text: str) -> list[tuple[str, str, DependencyGroup]]:
    """Parse ``paket.lock`` text into ``(name, version, group)`` tuples.

    The lockfile is organized into:

    * Top-level (no ``GROUP`` directive) → Main group, PROD.
    * ``GROUP <name>`` directives → switch to that group's mapping.

    Within a group, ``NUGET`` source sections list resolved entries.
    Other source sections (``GIT``, ``GITHUB``, ``HTTP``) are skipped
    because licenseal does not resolve from those.

    Indented entries (``    Pkg (1.0)``) at indent depth 4 are direct
    resolved packages; deeper indentation marks transitive children.
    Both surface as dependencies — Paket's lockfile model already
    flattens the resolution; the transitive walker doesn't re-derive.
    """
    out: list[tuple[str, str, DependencyGroup]] = []
    current_group = DependencyGroup.PROD
    in_nuget_source = False
    for raw_line in text.splitlines():
        stripped = raw_line.strip()
        if not stripped:
            continue
        group_match = _GROUP_LOCK_RE.match(raw_line)
        if group_match:
            current_group = _group_to_dependency_group(group_match.group(1))
            in_nuget_source = False
            continue
        if stripped == _NUGET_SOURCE_LINE:
            in_nuget_source = True
            continue
        if stripped in _NON_NUGET_SOURCE_LINES:
            in_nuget_source = False
            continue
        if stripped.startswith("remote:") or stripped.startswith("specs:"):
            # Source URL line or specs marker — informational only.
            continue
        if not in_nuget_source:
            continue
        entry_match = _LOCK_ENTRY_RE.match(raw_line)
        if not entry_match:
            continue
        name = entry_match.group(2).strip()
        version_raw = entry_match.group(3).strip()
        # Skip dependency-edge lines that DON'T look like resolved-version
        # lines. A resolved entry has a concrete version (e.g., ``13.0.1``);
        # an edge has a constraint (``>= 5.0``). The resolver treats both
        # the same way (constraints get UNKNOWN; concrete pins resolve).
        out.append((name, version_raw, current_group))
    return out


def discover_paket_dependencies(
    project_path: Path,
    *,
    exclude_paths: frozenset[Path] = frozenset(),
) -> tuple[list[Dependency], int]:
    """Discover Paket-managed dependencies under ``project_path``.

    Looks for ``paket.dependencies`` files; each file is treated as the
    manifest for its own subtree. Returns ``(deps, filtered_count)``.
    ``filtered_count`` is always 0 — Paket has no workspace-local concept
    (a sibling project reference goes through ``.csproj``'s
    ``<ProjectReference>`` mechanism, not through Paket).

    Both ``paket.dependencies`` and ``paket.lock`` are read where present.
    When the lockfile exists alongside the manifest, the lockfile's
    resolved entries take precedence (lockfile-first posture); the
    manifest still contributes group attribution for the directs.
    """
    out: list[Dependency] = []

    for deps_path in walk_project_files(
        project_path, _DEPENDENCIES_FILENAME, exclude_paths=exclude_paths
    ):
        text = decode_text(deps_path)
        if text is None:
            continue
        entries = _parse_paket_dependencies_text(text)
        source = deps_path.relative_to(project_path).as_posix()
        for name, version, group in entries:
            out.append(
                Dependency(
                    name=name,
                    version_constraint=version,
                    ecosystem=Ecosystem.DOTNET,
                    group=group,
                    source=source,
                )
            )

    return out, 0


def find_paket_lockfiles(
    project_path: Path,
    *,
    exclude_paths: frozenset[Path] = frozenset(),
) -> list[Path]:
    """Return every ``paket.lock`` under ``project_path``.

    The transitive walker uses these as resolved-graph source-of-truth
    when a Paket-managed project has both a manifest and a lockfile.
    """
    return walk_project_files(project_path, _LOCK_FILENAME, exclude_paths=exclude_paths)


def parse_paket_lock(
    path: Path,
    *,
    project_path: Path,
) -> list[Dependency]:
    """Parse one ``paket.lock`` file into a list of :class:`Dependency`.

    Unlike the discovery wrapper, this function takes a single lockfile
    path (used by the transitive walker after :func:`find_paket_lockfiles`
    has located the file). Returns an empty list on read errors;
    individual malformed lines within the file are silently skipped.
    """
    text = decode_text(path)
    if text is None:
        return []
    entries = _parse_paket_lock_text(text)
    source = path.relative_to(project_path).as_posix()
    return [
        Dependency(
            name=name,
            version_constraint=version,
            ecosystem=Ecosystem.DOTNET,
            group=group,
            source=source,
        )
        for name, version, group in entries
    ]
